spring:
  datasource:
    url: jdbc:mysql://localhost:3306/infoman1_db_manager
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

mysql:
  admin:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    username: ${MYSQL_ADMIN_USER:root}
    password: ${MYSQL_ADMIN_PASSWORD:1234}